### ISSUE TITLE
Repository not added to Gentoo's list

### ISSUE THREAD

**Issue by konsolebox** [xoores/gentoo-overlay#1]
I found your repository by searching `x11-plugins/x11-emoji-picker` and I notice it isn't added in Gentoo's list of repositories so I can't add it through eselect-repository or layman.  I only found xoreos which has a peculiarly similar link which is https://github.com/xoreos/gentoo-overlay.

I added your repository manualy through repos.conf but I also found an issue: [layout.conf](https://github.com/xoores/gentoo-overlay/blob/main/metadata/layout.conf) and [repo_name](https://github.com/xoores/gentoo-overlay/blob/main/profiles/repo_name) don't specify the same repo name.

I no longer use x11-plugins/x11-emoji-picker (I now use [emote](https://github.com/tom-james-watson/Emote)) but I thought it's still worth telling you this.

**Comment by xoores** [comment]
Hi,

Xoreos is unrelated to me, never heard of that 😅

It is true that I never applied to be added to any official repo etc - athough I'm quite sure that someone from Gentoo has seen this repo as I saw multiple packages making their way into an upstream, which I'm glad for :slightly_smiling_face:

Thanks for the info, you are absolutely right, I completely missed that! Will fix that.

**Comment by xoores** [comment]
Fixed in ea7d535

Thanks for reporting!
